/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-05 06:56:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1641191362848L));
    _jspx_dependants.put("/WEB-INF/views/templates/header.jsp", Long.valueOf(1641287019072L));
    _jspx_dependants.put("jar:file:/C:/kappa/playground/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semiprojectv1/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>SemiProjectV1-liset</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/base.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        table { width: 75%; margin: 25px auto; \r\n");
      out.write("                border-collapse: collapse; table-layout: fixed; }\r\n");
      out.write("        /* 테이블 여백, 테두리 설정, 크기 고정 */\r\n");
      out.write("        \r\n");
      out.write("        th, td { border: 1px solid black; padding: 10px;\r\n");
      out.write("                 text-align: center }\r\n");
      out.write("        \r\n");
      out.write("        td:nth-of-type(2) { white-space: nowrap;\r\n");
      out.write("                            overflow: hidden; text-overflow: ellipsis }\r\n");
      out.write("        /* 2번째 td 줄바꿈 제거, 넘치는 글자는 숨김 후 줄임표시 */\r\n");
      out.write("        \r\n");
      out.write("        tr:last-child td { border: none; }\r\n");
      out.write("        /* 맨마지막 행의 모든 td들의 테두리 제거 */\r\n");
      out.write("        \r\n");
      out.write("        .cpage { color: red; font: 35px bold; }\r\n");
      out.write("        /* 현재페이지 스타일 지정 */\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write(" <header>\r\n");
      out.write("   <h1>세미프로젝트v1</h1> <!-- 타이틀 -->\r\n");
      out.write("   <nav>\r\n");
      out.write("       <ul>\r\n");
      out.write("           <li><a href=\"index\">Home</a></li>\r\n");
      out.write("           <li><a href=\"join\">회원가입</a></li>\r\n");
      out.write("           <li><a href=\"login\">로그인</a></li>\r\n");
      out.write("           <li><a href=\"list\">게시판</a></li>\r\n");
      out.write("           <li><a href=\"myinfo\">회원정보</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </nav> <!-- 상단메뉴 -->\r\n");
      out.write("   <hr> <!-- 구분선 -->\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("            <h3>게시판</h3>\r\n");
      out.write("            <table>\r\n");
      out.write("               <colgroup>\r\n");
      out.write("                   <col style=\"width:10%\">\r\n");
      out.write("                   <col style=\"width:\">\r\n");
      out.write("                   <col style=\"width:15%\">\r\n");
      out.write("                   <col style=\"width:15%\">\r\n");
      out.write("                   <col style=\"width:10%\">\r\n");
      out.write("               </colgroup> <!-- 테이블컬럼스타일 -->\r\n");
      out.write("               \r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>번호</th>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <th>작성자</th>\r\n");
      out.write("                        <th>작성일</th>\r\n");
      out.write("                        <th>조회수</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead> <!-- 제목행 -->\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>23</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>24</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>25</td>\r\n");
      out.write("                        <td>시간은 금이라구, 친구! 진짜라구, 친구! 정말이라구, 친구! 참말이라구, 친구!</td>\r\n");
      out.write("                        <td>kappa</td>\r\n");
      out.write("                        <td>2021-12-28</td>\r\n");
      out.write("                        <td>887</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"5\">\r\n");
      out.write("                            <span> ◁ ◀\r\n");
      out.write("                            <span class=\"cpage\">1</span> 2 3 4 5 6 7 8 9 10 ▶ ▷ </span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody> <!-- 본문행 -->\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write(" <header>\r\n");
      out.write("   <h1>세미프로젝트v1</h1> <!-- 타이틀 -->\r\n");
      out.write("   <nav>\r\n");
      out.write("       <ul>\r\n");
      out.write("           <li><a href=\"index\">Home</a></li>\r\n");
      out.write("           <li><a href=\"join\">회원가입</a></li>\r\n");
      out.write("           <li><a href=\"login\">로그인</a></li>\r\n");
      out.write("           <li><a href=\"list\">게시판</a></li>\r\n");
      out.write("           <li><a href=\"myinfo\">회원정보</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </nav> <!-- 상단메뉴 -->\r\n");
      out.write("   <hr> <!-- 구분선 -->\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
